    <form method="post" action="bid.php">
        <label for="locaction">Where do you want to travel?</label>
        <?php echo $this->autoComplete("location",
                                       "",
                                       array('source' => array('New York',
                                                             'Mexico City',
                                                             'Sydney',
                                                             'Ruegen',
                                                             'Baden Baden'))); ?>
        <br />
     
        <label for="startDate">Travel Start Date:</label>
        <?php echo $this->datePicker("startDate", '',
                 array(
                    'defaultDate' => '+7',
                    'minDate' => '+7',
                    'onClose' => new Zend_Json_Expr(
                    	'function(){ window.alert("javascript function encoded by Zend_Json") }'))); ?>
        <br />
     
        <label for="startDate">Travel End Date:</label>
        <?php echo $this->datePicker("endDate", '',
                 array(
                    'defaultDate' => '+14',
                    'minDate' => '+7',
                    'onClose' => new Zend_Json_Expr(
                    	'function(){ window.alert("javascript function encoded by Zend_Json") }'))); ?>
        <br />
     
        <label for="bid">Your Bid:</label>
        <?php echo $this->spinner("bid",
                                  "",
                                  array('min' => 1205.50,
                                        'max' => 10000,
                                        'start' => 1205.50,
                                        'currency' => '€')); ?>
        <br />
     
        <input type="submit" value="Bid!" />
    </form>
    <?php echo $this->l('Testing','user/user');?>